progress

diff --git a/narun b/narun
--- a/narun
+++ b/narun
@@ -4,67 +4,55 @@
 # This is a shell script for using the Nautilus cluster at https://nautilus.optiputer.net
 #
 
-getopt --test > /dev/null
-if [[ $? -ne 4 ]]; then
-    echo "I’m sorry, `getopt --test` failed in this environment."
-    exit 1
-fi
+parse_command_line_parameters()
 
-OPTIONS=dfo:v
-LONGOPTIONS=debug,force,output:,verbose
+echo YAML=$YAML GPUS=$GPUS CPUS=$CPUS MEM=$MEM SYNC_FROM=$SYNC_FROM SYNC_TO=$SYNC_TO
 
-# -temporarily store output to be able to check for errors
-# -e.g. use “--options” parameter by name to activate quoting/enhanced mode
-# -pass arguments only via   -- "$@"   to separate them correctly
-PARSED=$(getopt --options=$OPTIONS --longoptions=$LONGOPTIONS --name "$0" -- "$@")
-if [[ $? -ne 0 ]]; then
-    # e.g. $? == 1
-    #  then getopt has complained about wrong arguments to stdout
-    exit 2
-fi
-# read getopt’s output this way to handle the quoting right:
-eval set -- "$PARSED"
 
-# now enjoy the options in order and nicely split until we see --
-while true; do
-    case "$1" in
+#
+# Functions below implement the various components of the script
+parse_command_line_parameters(){
+    PARAMS=""
+
+    while (( "$#" )); do
+      case "$1" in
         -y|--yaml)
-            YAML=y
-            shift
-            ;;
+          YAML=$2
+          shift 2
+          ;;
         -g|--gpus)
-            GPUS=g
-            shift
-            ;;
+          GPUS=$2
+          shift 2
+          ;;
         -c|--cpus)
-            CPUS=c
-            shift
-            ;;
+          CPUS=$2
+          shift 2
+          ;;
         -m|--mem)
-            MEM=m
-            shift
-            ;;
-	-s|--sync)
-	    SYNC_FROM=${SYNC_FROM}:${2}
-	    SYNC_TO=${SYNC_TO}:${2}
-	    shift 2
-	    ;;
-        --)
-            shift
-            break
-            ;;
-        *)
-            echo "Programming error"
-            exit 3
-            ;;
-    esac
-done
+          MEM=$2
+          shift 2
+          ;;
+        -s|--sync)
+          SYNC_FROM=${SYNC_FROM}:${2}
+          SYNC_TO=${SYNC_TO}:${3}
+          shift 3
+          ;;
+        --) # end argument parsing
+          shift
+          break
+          ;;
+        -*|--*=) # unsupported flags
+          echo "Error: Unsupported flag $1" >&2
+          exit 1
+          ;;
+        *) # preserve positional arguments
+          PARAM="$PARAMS $1"
+          shift
+          ;;
+      esac
+    done
 
-# handle non-option arguments
-if [[ $# -ne 1 ]]; then
-    echo "Options: --yaml ${YAML} --gpus ${GPUS} --cpus ${CPUS} --mem ${MEM} --sync ${SYNC}"
-    echo "Run command: $0"
-    exit 4
-fi
+    # set positional arguments in their proper place
+    eval set -- "$PARAMS"
 
-echo "END"
+}
