skeleton working

diff --git a/narun b/narun
--- a/narun
+++ b/narun
@@ -15,61 +15,55 @@ DEFAULT_MEM=4GB
 #
 # Functions below implement the various components of the script
 #
-parse_command_line_parameters() {
-echo $@
-    PARAMS=""
-
-    while (( "$#" )); do
-        case "$1" in
-            -y|--yaml)
-                YAML=$2
-                shift 2
-                ;;
-            -g|--gpus)
-                GPUS=$2
-                shift 2
-                ;;
-            -c|--cpus)
-                CPUS=$2
-                shift 2
-                ;;
-            -m|--mem)
-                MEM=$2
-                shift 2
-                ;;
-            -s|--sync)
-                SYNC_FROM=${SYNC_FROM}:${2}
-                SYNC_TO=${SYNC_TO}:${3}
-                shift 3
-                ;;
-            --) # end argument parsing
-                shift
-                break
-                ;;
-            -*|--*=) # unsupported flags
-                echo "Error: Unsupported flag $1" >&2
-                exit 1
-                ;;
-            *) # preserve positional arguments
-                PARAM="$PARAMS $1"
-                shift
-                ;;
-        esac
-    done
-
-    # set positional arguments in their proper place
-    eval set -- "$PARAMS"
-
-    echo YAML=$YAML GPUS=$GPUS CPUS=$CPUS MEM=$MEM SYNC_FROM=$SYNC_FROM SYNC_TO=$SYNC_TO
+run_script(){
+    echo "TODO - Launch POD and connect to process"
+    echo "ARGS: YAML=$YAML GPUS=$GPUS CPUS=$CPUS MEM=$MEM SYNC_FROM=$SYNC_FROM SYNC_TO=$SYNC_TO"
 }
 
 #
-# Main script body
+# Command line parsing
 #
-echo $@
-parse_command_line_parameters
+PARAMS=""
 
+while (( "$#" )); do
+    case "$1" in
+        -y|--yaml)
+            YAML=$2
+            shift 2
+            ;;
+        -g|--gpus)
+            GPUS=$2
+            shift 2
+            ;;
+        -c|--cpus)
+            CPUS=$2
+            shift 2
+            ;;
+        -m|--mem)
+            MEM=$2
+            shift 2
+            ;;
+        -s|--sync)
+            SYNC_FROM=${SYNC_FROM}:${2}
+            SYNC_TO=${SYNC_TO}:${3}
+            shift 3
+            ;;
+        --) # end argument parsing
+            shift
+            break
+            ;;
+        -*|--*=) # unsupported flags
+            echo "Error: Unsupported flag $1" >&2
+            exit 1
+            ;;
+        *) # preserve positional arguments
+            PARAM="$PARAMS $1"
+            shift
+            ;;
+    esac
+done
 
-echo YAML=$YAML GPUS=$GPUS CPUS=$CPUS MEM=$MEM SYNC_FROM=$SYNC_FROM SYNC_TO=$SYNC_TO
+# set positional arguments in their proper place
+eval set -- "$PARAMS"
 
-
+run_script
